/**
 * Google Ads / Website Tracking
 * Google Ads Account: AW-18413488434
 */

const GOOGLE_ADS_ID = "AW-18413488434";

type GtagFunction = (...args: any[]) => void;

function getGtag(): GtagFunction | undefined {
  if (typeof window === "undefined") return undefined;

  return (
    window as Window & {
      gtag?: GtagFunction;
    }
  ).gtag;
}

/**
 * Track a general website event
 */
export function trackEvent(
  eventName: string,
  parameters: Record<string, unknown> = {}
) {
  const gtag = getGtag();

  if (!gtag) {
    console.warn("Google gtag is not available");
    return;
  }

  gtag("event", eventName, parameters);
}

/**
 * Track Google Ads conversion
 *
 * IMPORTANT:
 * Replace conversionLabel with the actual label
 * generated by Google Ads.
 */
export function trackConversion(
  conversionLabel: string,
  options: {
    value?: number;
    currency?: string;
    transactionId?: string;
  } = {}
) {
  const gtag = getGtag();

  if (!gtag) {
    console.warn("Google gtag is not available");
    return;
  }

  gtag("event", "conversion", {
    send_to: `${GOOGLE_ADS_ID}/${conversionLabel}`,
    value: options.value ?? 1.0,
    currency: options.currency ?? "INR",
    ...(options.transactionId
      ? {
          transaction_id: options.transactionId,
        }
      : {}),
  });
}

/**
 * Track CTA button clicks
 */
export function trackCTA(
  ctaName: string,
  location?: string
) {
  trackEvent("cta_click", {
    cta_name: ctaName,
    location: location ?? "unknown",
  });
}

/**
 * Track phone number clicks
 */
export function trackPhoneClick(
  phoneNumber?: string,
  location?: string
) {
  trackEvent("phone_click", {
    phone_number: phoneNumber ?? "unknown",
    location: location ?? "unknown",
  });
}

/**
 * Track WhatsApp clicks
 */
export function trackWhatsAppClick(
  location?: string
) {
  trackEvent("whatsapp_click", {
    location: location ?? "unknown",
  });
}

/**
 * Track email clicks
 */
export function trackEmailClick(
  email?: string,
  location?: string
) {
  trackEvent("email_click", {
    email: email ?? "unknown",
    location: location ?? "unknown",
  });
}

/**
 * Track form submissions
 */
export function trackFormSubmission(
  formName: string,
  parameters: Record<string, unknown> = {}
) {
  trackEvent("form_submit", {
    form_name: formName,
    ...parameters,
  });
}

/**
 * Track car/model views
 */
export function trackCarModelView(
  modelName: string
) {
  trackEvent("car_model_view", {
    model_name: modelName,
  });
}

/**
 * Track car/model selection
 */
export function trackCarModelSelect(
  modelName: string
) {
  trackEvent("car_model_select", {
    model_name: modelName,
  });
}

/**
 * Track brochure downloads
 */
export function trackBrochureDownload(
  modelName?: string
) {
  trackEvent("brochure_download", {
    model_name: modelName ?? "unknown",
  });
}

/**
 * Track external link clicks
 */
export function trackExternalLink(
  url: string,
  location?: string
) {
  trackEvent("external_link_click", {
    url,
    location: location ?? "unknown",
  });
}

/**
 * Track scroll depth
 */
export function trackScrollDepth(
  percentage: number
) {
  trackEvent("scroll_depth", {
    percentage,
  });
}

/**
 * Track video interactions
 */
export function trackVideoEvent(
  action: "start" | "complete" | "progress",
  videoName: string,
  percentage?: number
) {
  trackEvent("video_interaction", {
    action,
    video_name: videoName,
    ...(percentage !== undefined
      ? { percentage }
      : {}),
  });
}